packagegroup-samples: no need to add PN in PACKAGES
PN has been in PACKAGES. It is not necessary to add it again.

The packagegroup-samples do_package error information is as following:
======================================================================
ERROR: QA Issue: packagegroup-samples is listed in PACKAGES multiple
times, this leads to packaging errors. [packages-list]

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>