glib-2.0-native: work around the build failure with gcc >=6.0
-Wformat-security cannot be used separately with gcc >= 6.0 'cause
it will be ignored without specifying -Wformat. This fix resolves
the following build failure:

build-helios/tmp/work/x86_64-linux/glib-2.0-native/1_2.44.1-r0/glib-2.44.1/glib/gdate.c:2497:7:
error: format not a string literal, format string not checked
[-Werror=format-nonliteral]
|        tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
|        ^~~~~~

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>