grub-efi: Add the ALTERNATIVE to avoid the co-exist commands in grub-efi and grub recipes.
Update the system grub-efi rpm will print the following error information:
========================================================================================
error: file /usr/bin/grub-editenv from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-fstest from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-menulst2cfg from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-mkimage from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-mklayout from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-mkpasswd-pbkdf2 from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-mkrelpath from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/bin/grub-script-check from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/sbin/grub-bios-setup from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/sbin/grub-ofpathname from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64
error: file /usr/sbin/grub-probe from install of
grub-efi-2.00-r3.fix0.1.core2_64 conflicts with file from package grub-2.00-r1.0.core2_64

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>