haccmds: Fix haccmds miss perl RDEPENDS QA Issue in RPM4
This issue comes from latest oe-core commit
586875cea5769fea7d17bae2677eab72e4fc7e31

rpm: Disable perl dependency generation

Missing the perl RDEPENDS QA Issue is as following:
======================================================
ERROR: haccmds-1.0-r0 do_package_qa: QA Issue: /usr/sbin/registerTarget contained in package haccmds requires /usr/bin/perl, but no providers
found in RDEPENDS_haccmds? [file-rdeps]
ERROR: haccmds-1.0-r0 do_package_qa: QA run found fatal errors. Please consider fixing them.
ERROR: haccmds-1.0-r0 do_package_qa: Function failed: do_package_qa

Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>