pkgconfig-native: work around the build failure with gcc >=6.0
-Wformat-security cannot be used separately with gcc >= 6.0 'cause
it will be ignored without specifying -Wformat. This fix resolves
the following build failure:

build-helios/tmp/work/x86_64-linux/pkgconfig-native/0.28+gitAUTOINC+40342dd0ea-r0/git/glib/glib/gdate.c:2497:7:
error: format not a string literal, format string not checked
[-Werror=format-nonliteral]
       tmplen = strftime (tmpbuf, tmpbufsize, locale_format, &tm);
       ^~~~~~

Signed-off-by: Lans Zhang <jia.zhang@windriver.com>