cube-builder-initramfs: Fix build order dependency problem
If building a package that depends on the cube-builder-initramfs it
may try to build from sstate and not have all its dependencies met,
which cause it to fail with an error like:

ERROR: cube-builder-initramfs-1.0-r0 do_image_complete: Error executing a python function in exec_python_func() autogenerated:
Exception: FileNotFoundError: [Errno 2] No such file or directory: '/opt/build/tmp/deploy/licenses/ovmf/recipeinfo'

Signed-off-by: Jason Wessel <jason.wessel@windriver.com>