let inetutils rprovides telnet and rsh
When using the rpmbuild to build lynx srpm, this srpm requires rsh and telnet.
If the project uses the inetutils recipe to provide these tools and packages,
it would not find the required dependence provides packages.
So we have to use this method to work around this issue.

rpmbuild lynx.src.rpm build error information is as following:
===============================================================
rpmbuild --rebuild lynx-2.8.8-0.3.dev15.el7.src.rpm
Installing lynx-2.8.8-0.3.dev15.el7.src.rpm
error: Failed build dependencies:
        openssl-devel is needed by lynx-2.8.8-0.3.dev15.src
        ncurses-devel is needed by lynx-2.8.8-0.3.dev15.src
        rsh is needed by lynx-2.8.8-0.3.dev15.src
        slang-devel is needed by lynx-2.8.8-0.3.dev15.src
        telnet is needed by lynx-2.8.8-0.3.dev15.src
        zlib-devel is needed by lynx-2.8.8-0.3.dev15.src

Signed-off-by: fupan li <fupan.li@windriver.com>
Signed-off-by: Guojian Zhou <guojian.zhou@windriver.com>